WIP: Feature/gitea
StaticJsCMS/static-cms pull request #325
Opened 2023-01-10 20:44 UTC by denyskon

See #310 

Work in progress!

2023-01-10 20:55 UTC, denyskon commented
Login, initial collection loading and media library are working. When opening a collection item, I get some weird issue where the media_folder gets split into single characters and sent as single requests, I'll take another look at it tomorrow......

2023-01-12 19:22 UTC, KaneFreeman commented
> I get some weird issue where the media_folder gets split into single characters and sent as single requests

That was a different bug that was fixed in beta 11. Please update your branch and test again.

2023-01-12 19:47 UTC, denyskon commented
> > I get some weird issue where the media_folder gets split into single characters and sent as single requests
> 
> That was a different bug that was fixed in beta 11. Please update your branch and test again.

Thanks, that is working now. I had a temporary fix, for that, but I rebased to main now.

I have two issues I don't know the structure good enough to understand them:

1. Loading the collection items works fine, but the link to the item when clicking on a tile has the folder path in it for some reason. Example:
  - http://localhost:8080/backends/gitea/#/collections/pages/entries/content%2Fgerman%2Fpages/bibo -> Wrong
  - http://localhost:8080/backends/gitea/#/collections/pages/entries/bibo -> Right
2. The media tab on the homepage is working fine, but any media library popup when editing an entry says no media found.

Do you have any ideas what the reason could be? @KaneFreeman

2023-01-15 21:43 UTC, denyskon commented
Tests are a hell, but seems like it's ready. @KaneFreeman could you take a look, and merge if everything is okay?

2023-01-17 13:40 UTC, KaneFreeman requested changes
Looks like you have a few linting/formatting issues. Please run `yarn format` to correct those.

2023-01-17 13:40 UTC, KaneFreeman commented on packages/docs/content/docs/backends-overview.mdx
> +| base_url      | string                                                                                                  | GitHub or Bitbucket<br />`https://api.netlify.com`<br /><br />GitLab<br />`
```suggestion
| base_url      | string                                                                                                  | GitHub or Bitbucket<br />`https://api.netlify.com`<br /><br />GitLab<br />`https://gitlab.com`                                                                                                 | _Optional_. OAuth client hostname (just the base domain, no path). **Required** when using an external OAuth server or self-hosted GitLab/Gitea|
```

2023-01-17 13:40 UTC, KaneFreeman commented on packages/docs/content/docs/backends-overview.mdx
> +| api_root      | string                                                                                                  | GitHub<br />`https://api.github.com`<br /><br />GitLab<br/>`https://gitlab.
Small formatting issue here.

```suggestion
| api_root      | string                                                                                                  | GitHub<br />`https://api.github.com`<br /><br />GitLab<br/>`https://gitlab.com/api/v4`<br /><br />Bitbucket<br />`https://api.bitbucket.org/2.0`<br /><br />Gitea<br />`https://try.gitea.io/api/v1` | _Optional_. The API endpoint. Only necessary in certain cases, like with GitHub Enterprise or self-hosted GitLab                                                 |
```

2023-01-17 13:40 UTC, KaneFreeman commented on packages/docs/content/docs/gitea-backend.mdx
> +weight: 70
This should appear before `Local Backend` (which has a weight of 50).
```suggestion
weight: 45
```

2023-01-17 13:40 UTC, KaneFreeman commented on packages/core/src/backends/gitea/__tests__/implementation.spec.ts
> +describe('github backend implementation', () => {
Can we clean up the use of `github` throughout the tests.

2023-01-17 13:40 UTC, KaneFreeman commented on packages/docs/content/docs/gitea-backend.mdx
> +group: Backends
Please add

```
beta: true
```

This will mark this whole documentation page (and the gitea backend) as beta.

2023-01-17 23:08 UTC, KaneFreeman approved these changes

2023-01-17 23:08 UTC, merged