Update bundling documentation with an example using Astro
StaticJsCMS/static-cms pull request #358
Opened 2023-01-15 14:32 UTC by Skrubbadubba

2023-01-15 16:04 UTC, Skrubbadubba commented on packages/docs/content/docs/add-to-your-site-bundling.mdx
> +**Note**: Because `config.<js/yml>` is requested via http, make sure `<siteurl>/admin/config.<js/yml>` exists as an endpoint on your build. If the file is not placed in the public folder, this might
I'm not sure this is right. This is how it looked to work to me after some trial and error.

2023-01-15 16:05 UTC, Skrubbadubba commented on packages/docs/content/docs/add-to-your-site-bundling.mdx
> +If the CMS object is initialized without being passed an object with a valid config attribute, it will try to fetch and read a `config.yml` or `config.js` file, via http, within the same path where t
I'm not sure this is right. This is how it looked to work to me after some trial and error.

2023-01-15 16:08 UTC, Skrubbadubba commented on packages/docs/content/docs/add-to-your-site-bundling.mdx
> +npm install @staticcms/core@next
This will obviously be changed after 1.0.0 release, but I thought this should be added, as the docs should ideally only show working code.

2023-01-15 16:19 UTC, Skrubbadubba commented on packages/docs/content/docs/add-to-your-site-bundling.mdx
> +**Note**: Because `config.<js/yml>` is requested via http, make sure `<siteurl>/admin/config.<js/yml>` exists as an endpoint on your build. If the file is not placed in the public folder, this might
"framework" or "static site generator". Wasn't sure what was most appropriate

2023-01-16 22:44 UTC, KaneFreeman requested changes

2023-01-16 22:44 UTC, KaneFreeman commented on packages/docs/content/docs/add-to-your-site-bundling.mdx
> +**Note**: Because `config.<js/yml>` is requested via http, make sure `<siteurl>/admin/config.<js/yml>` exists as an endpoint on your build. If the file is not placed in the public folder, this might
`static site generator`

2023-01-16 22:44 UTC, KaneFreeman commented on packages/docs/content/docs/add-to-your-site-bundling.mdx
> +### Example using [Astro](https://astro.build)
Right now I would like to avoid having any framework/platform specific details in the guide. Having that in here makes this into a maintenance issue, due to having to keep up with the platform in question to ensure our docs are accurate. I do not have the time, nor is our community big enough yet, to support that.

2023-01-17 18:03 UTC, KaneFreeman approved these changes

2023-01-17 18:10 UTC, merged