Fix variable.
StaticJsCMS/static-cms pull request #665
Opened 2023-03-15 22:38 UTC by vseventer

## This Pull Request:
- Fixes what I'm pretty sure is a typo in the memo on determining the collection URL.

## Why is this PR needed?
I ran into the same issue with nested collections as reported in #63 - https://github.com/StaticJsCMS/static-cms/issues/63#issuecomment-1438384129

The error points at the line changed in this PR, and after this commit I am able to successfully enter nested collections via the nav tree.

2023-03-22 21:59 UTC, KaneFreeman requested changes

2023-03-22 21:59 UTC, KaneFreeman commented on packages/core/src/components/Collection/Collection.tsx
> -      if (filterTerm) {
I am not sure the `filterTerm` check should be removed.

I will need to test this a bit.

Also could you point yiur PR to the `next` branch. As this will go out in v2. As there are some UI changes for nested collections coming too.

2023-03-22 23:42 UTC, vseventer commented on packages/core/src/components/Collection/Collection.tsx
> -      if (filterTerm) {
Updated the PR base.

Regarding `filterTerm` - on line 91 there is already a truthy check. So, if line 91 evaluates to true, then an additional `if (filterTerm)` will always evaluate to true, hence it can be left out.

2023-03-26 22:32 UTC, KaneFreeman approved these changes

2023-03-26 22:32 UTC, merged